on: 
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Rust Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        components: rustfmt, clippy
    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: | 
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          ${{ runner.os }}-cargo-
    - name: Cache Target
      uses: actions/cache@v4
      with:
        path: target/
        key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
          ${{ runner.os }}-target-
    - name: Install Trunk
      run: cargo install trunk
    - name: Build
      run: trunk build
    - name: Tests
      run: cargo test
    - name: Fmt Lint
      run: cargo fmt --all -- --check
    - name: Clippy Lint
      run: cargo clippy -- -D warnings
